### ISSUE TITLE
Dev-tools

### ISSUE THREAD

**Issue by smooJitter** [underscopeio/reduxable#16]
What about middleware (logger) and store enhancers(dev-tools)?  Promising for sure, the thing I like most about redux are the dev tools. What shows up as the action dispatch.

**Comment by gaguirre** [comment]
It works out of the box. In the store creation just use the middlewares/enhancers you want to use.
Since Reduxable uses `dispatch` internally you will see all the actions dispatched in your logs.

Thanks for the question, I'll add a **FAQ** section to the README.
